name: Github Action First Demo
on: push
jobs: 
    first-job-on-windows-and-ubuntu-computer:
        runs-on: ubuntu-latest
        steps:
          - run: node -v
          - run: npm -v
          - run: node index.js