name: Github Action First Demo
on: push
jobs: 
    first-job-on-windows-and-ubuntu-computer:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: node -v
          - run: npm -v
          - run: node index.js
          - run: npm run lint